--- # start of yaml file
- name: Install and start Nginx  #- represents list of elements
  hosts: all                     # run on all target servers listed in inventory file
  become: true                   #run tasks with sudo/root privileges

  tasks:
    - name : Ensure Nginx is installed
      apt:        # shell: apt install nginx (is also works). but apt is an ansible mode and it is more generic and reliable
        name: nginx
        state : present  # Ensure the package is installed
    - name : Start Nginx service
      service:     # shell:systemctl start nginx
        name: nginx
        state: started 
      
  
